### ISSUE TITLE
Can I catch client disconnects on server-side?

### ISSUE THREAD

**Issue by c00kiemonster** [zeekay/flask-uwsgi-websocket#53]
On the client-side it is easy to use the `onclose` function to detect when the server drops off.

**But how about on the server-side, how can the server detect when a client has disconnected?**

I ran the pubsub-asyncio example and I can see the `redis_subscribe` function exits when a message is sent to a disconnected client. But how can I detect the client disconnect event in itself?

I don’t want to rely on sending ping like messages just to detect disconnected clients. Websockets already have a ping/pong mechanism, I’d just be reinventing the wheel adding more complexity.

**Comment by stepheny** [comment]
I'm so sorry that I've made a mistake and there was bug, it should be fixed now.

> But how about on the server-side, how can the server detect when a client has disconnected?
By design, once client disconnected, the next server receive should got a None.
In the pubsub-asyncio example, there is a "busy" wait while True loop, once the client disconnected, it should break. I'm sorry about the bug that corrupted this.
An onclose call back could be triggered before break or after the loop, or just inline your code there.

**Comment by c00kiemonster** [comment]
Great stuff! Many Thanks!
